language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --no-interaction

script:
  - cd tests
  - ../vendor/bin/phpunit --coverage-clover coverage.xml --configuration phpunit.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
