language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install --no-interaction

script:
  - cd tests
  - phpunit --coverage-clover coverage.xml --configuration phpunit.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
